# Generated by Django 4.1.2 on 2022-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user',
            new_name='follower',
        ),
    ]
