# Generated by Django 4.1.2 on 2022-12-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truth',
            old_name='author',
            new_name='voter',
        ),
    ]
