# Generated by Django 4.1.2 on 2022-12-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_author_truth_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
